//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.09.25 at 01:20:57 AM IST 
//


package com.planetclubs.model;

import java.io.Serializable;
import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;



@Entity
@Table(name = "corporate")
public class Corporate implements Serializable{


private static final long serialVersionUID = 1L;

	@Id
    @GeneratedValue
    @Column(name="id")
    protected int id;
	

	@Column(name = "name")
    protected String name;
	
	@Column(name = "address")
    protected String address;

	@Column(name = "contactEmail")
	protected String contactEmail;
    
	@Column(name = "contactNo")
    protected String contactNo;

    @Column(name = "emailDomain")
    protected String emailDomain;
    
    @Column(name = "doubleVerification")
    protected boolean doubleVerification;
    
    
	public int getId() {
		return id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public String getName() {
		return name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getAddress() {
		return address;
	}

	public void setAddress(String address) {
		this.address = address;
	}

	public String getContactEmail() {
		return contactEmail;
	}

	public void setContactEmail(String contactEmail) {
		this.contactEmail = contactEmail;
	}

	public String getContactNo() {
		return contactNo;
	}

	public void setContactNo(String contactNo) {
		this.contactNo = contactNo;
	}

	public String getEmailDomain() {
		return emailDomain;
	}

	public void setEmailDomain(String emailDomain) {
		this.emailDomain = emailDomain;
	}

	
	public boolean isDoubleVerification() {
		return doubleVerification;
	}

	public void setDoubleVerification(boolean doubleVerification) {
		this.doubleVerification = doubleVerification;
	}

	public static long getSerialversionuid() {
		return serialVersionUID;
	}
	
        
}
